// Purpose: To test the database inserts for the project.
import type {Game} from '../database/Sheet';
import { addGame } from '../database/sheets';
import type { SheetInfo } from '../database/SheetInfo';
import { addSheet } from '../database/sheets';
import type { Sheet } from '../database/Sheet';
import { addSheetInfo } from '../database/sheetinfos';
import type { GameStat } from '$lib/database/GameStats';
import { addGameStat } from '$lib/database/gamestat';
import type { IndividualScore } from '$lib/database/IndividualScores';
import { addIndividualScore } from '../database/individualscore';
import type { Penalty } from '../database/Penalty';
import { addPenalty } from '../database/penalties';
import type { Team } from '../database/Team';
import { addTeam } from '../database/teams';
import type { Timeout } from '../database/Timeout';
import { addTimeout } from '../database/timeouts';
import type { Save } from '../database/Save';
import { addSave } from '../database/saves';
import type { Player } from '../database/Team';
import { addPlayer } from '../database/teams';


export async function Complete_Insert_test(){
  dbinsert_Game();
  dbinsert_Sheet();
  dbinsert_Teams();
  dbinsert_Players();
  dbinsert_SheetInfo();
  dbinsert_Timeouts();
  dbinsert_Saves();
  dbinsert_Penalties();
  dbinsert_IndividualScore();
  dbinsert_GameStat();
  
}

async function dbinsert_Players() {
  const players: Player[] = [
    
    {
      team_id: "maple hawks",
      player_id: "terry davis",
      team_name: "Maple Hawks",
      player_name: "Terry Davis",
      player_number: 1,
      position: "Goalie",
      player_class: "Senior",
      hometown: 'Atlanta',
      state: 'Georgia',
      height_feet: 5,
      height_inches:11,
      weight: 190,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },
    {
      team_id: "maple hawks",
      player_id: "jarod wong",
      team_name: "Maple Hawks",
      player_name: "Jarod Wong",
      player_number: 3,
      position: "Defender",
      player_class: "Junior",
      hometown: "Durham",
      state: "North Carolina",
      height_feet: 6,
      height_inches: 2,
      weight: 210,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },
    {
      team_id: "maple hawks",
      player_id: "tom perry",
      team_name: "Maple Hawks",
      player_name: "Tom Perry",
      player_number: 5,
      position: "Defender",
      player_class: "",
      hometown: "Portland",
      state: "Oregon",
      height_feet: 6,
      height_inches: 1,
      weight: 200,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },
    {
      team_id: "maple hawks",
      player_id: "charles roy",
      team_name: "Maple Hawks",
      player_name: "Charles Roy",
      player_number: 1,
      position: "Defender",
      player_class: "",
      hometown: "San Bernardino",
      state: "California",
      height_feet: 5,
      height_inches: 9,
      weight: 180,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },
    {
      team_id: "maple hawks",
      player_id: "donald right",
      team_name: "Maple Hawks",
      player_name: "Donald Right",
      player_number: 40,
      position: "Midfielder",
      player_class: "",
      hometown: "Nashville-Davidson",
      state: "Tennessee",
      height_feet: 5,
      height_inches: 10,
      weight: 185,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },
    {
      team_id: "maple hawks",
      player_id: "jackson kaleb",
      team_name: "Maple Hawks",
      player_name: "Jackson Kaleb",
      player_number: 36,
      position: "Midfielder",
      player_class: "",
      hometown: "Greensboro",
      state: "North Carolina",
      height_feet: 5,
      height_inches: 8,
      weight: 175,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },
    {
      team_id: "maple hawks",
      player_id: "michael jones",
      team_name: "Maple Hawks",
      player_name: "Terry Cones",
      player_number: 18,
      position: "Midfielder",
      player_class: "",
      hometown: "Rochester",
      state: "New York",
      height_feet: 5,
      height_inches: 9,
      weight: 180,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },
    {
      team_id: "maple hawks",
      player_id: "robert sunny",
      team_name: "Maple Hawks",
      player_name: "Bob Sunny",
      player_number: 33,
      position: "Attacker",
      player_class: "",
      hometown: "Cleveland",
      state: "Ohio",
      height_feet: 6,
      height_inches: 0,
      weight: 210,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },
    {
      team_id: "maple hawks",
      player_id: "jerry davidson",
      team_name: "Maple Hawks",
      player_name: "Jerry Davidson",
      player_number: 12,
      position: "Attacker",
      player_class: "",
      hometown: "Honolulu",
      state: "Hawaii",
      height_feet: 5,
      height_inches: 10,
      weight: 185,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },
    {
      team_id: "maple hawks",
      player_id: "william elder",
      team_name: "Maple Hawks",
      player_name: "William Elder",
      player_number: 23,
      position: "Attacker",
      player_class: "",
      hometown: "San Francisco",
      state: "California",
      height_feet: 5,
      height_inches: 9,
      weight: 180,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },

    {
      team_id: "river raptors",
      player_id: "leon mack",
      team_name: "River Raptors",
      player_name: "Leon Mack",
      player_number: 12,
      position: "Goalie",
      player_class: "",
      hometown: "San Jose",
      state: "California",
      height_feet: 6,
      height_inches: 3,
      weight: 210,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },
    {
      team_id: "river raptors",
      player_id: "oscar flin",
      team_name: "River Raptors",
      player_name: "Oscar Flin",
      player_number: 1,
      position: "Defender",
      player_class: "",
      hometown: "Baton Rouge",
      state: "Louisiana",
      height_feet: 5,
      height_inches: 10,
      weight: 190,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },
    {
      team_id: "river raptors",
      player_id: "sam nickson",
      team_name: "River Raptors",
      player_name: "Sam Nickson",
      player_number: 1,
      position: "Defender",
      player_class: "",
      hometown: "Long Beach",
      state: "California",
      height_feet: 5,
      height_inches: 9,
      weight: 180,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },
    {
      team_id: "river raptors",
      player_id: "henry schalds",
      team_name: "River Raptors",
      player_name: "Henry Schalds",
      player_number: 1,
      position: "Defender",
      player_class: "",
      hometown: "Philadelphia",
      state: "Pennsylvania",
      height_feet: 6,
      height_inches: 2,
      weight: 210,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },
    {
      team_id: "river raptors",
      player_id: "cameron mercer",
      team_name: "River Raptors",
      player_name: "Cameron Mercer",
      player_number: 11,
      position: "Midfielder",
      player_class: "",
      hometown: "Washington",
      state: "District of Columbia",
      height_feet: 5,
      height_inches: 11,
      weight: 190,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "river raptors",
      player_id: "rudy mahoney",
      team_name: "River Raptors",
      player_name: "Rudy Mahoney",
      player_number: 5,
      position: "Midfielder",
      player_class: "",
      hometown: "Jacksonville",
      state: "Florida",
      height_feet: 5,
      height_inches: 10,
      weight: 185,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "river raptors",
      player_id: "brett malone",
      team_name: "River Raptors",
      player_name: "Brett Malone",
      player_number: 13,
      position: "Midfielder",
      player_class: "",
      hometown: "Laredo",
      state: "Texas",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },
    {
      team_id: "3",
      player_id: "jared mcclure",
      team_name: "River Raptors",
      player_name: "Jared Mcclure",
      player_number: 23,
      position: "Attacker",
      player_class: "",
      hometown: "Buffalo",
      state: "New York",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "3",
      player_id: "noel wagner",
      team_name: "River Raptors",
      player_name: "Noel Wagner",
      player_number: 9,
      position: "Attacker",
      player_class: "",
      hometown: "Huntington",
      state: "New York",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "3",
      player_id: "emmanuel hoffman",
      team_name: "River Raptors",
      player_name: "Emmanuel Hoffman",
      player_number: 62,
      position: "Attacker",
      player_class: "",
      hometown: "Phoenix",
      state: "Arizona",
      height_feet: 0,
      height_inches: 0,
      weight: 0, quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },

    {
      team_id: "3",
      player_id: "walter hoffman",
      team_name: "Sunset Stallions",
      player_name: "Walter Hoffman",
      player_number: 1,
      position: "Goalie",
      player_class: "",
      hometown: "Las Vegas",
      state: "Nevada",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },
    {
      team_id: "sunset stallions",
      player_id: "mitchel estrade",
      team_name: "Sunset Stallions",
      player_name: "Mitchel Estrade",
      player_number: 1,
      position: "Defender",
      player_class: "",
      hometown: "Plano",
      state: "Texas",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "sunset stallions",
      player_id: "rex walls",
      team_name: "Sunset Stallions",
      player_name: "Rex Walls",
      player_number: 1,
      position: "Defender",
      player_class: "",
      hometown: "Seattle",
      state: "Washington",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "sunset stallions",
      player_id: "nick reed",
      team_name: "Sunset Stallions",
      player_name: "Nick Reed",
      player_number: 1,
      position: "Defender",
      player_class: "",
      hometown: "Miami",
      state: "Florida",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },
    {
      team_id: "sunset stallions",
      player_id: "len whitney",
      team_name: "Sunset Stallions",
      player_name: "Len Whitney",
      player_number: 67,
      position: "Midfielder",
      player_class: "",
      hometown: "Santa Ana",
      state: "California",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "sunset stallions",
      player_id: "amos noble",
      team_name: "Sunset Stallions",
      player_name: "Amos Noble",
      player_number: 17,
      position: "Midfielder",
      player_class: "",
      hometown: "Baltimore",
      state: "Maryland",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "sunset stallions",
      player_id: "alex gillespire",
      team_name: "Sunset Stallions",
      player_name: "Alex Gillespire",
      player_number: 12,
      position: "Midfielder",
      player_class: "",
      hometown: "Mesa",
      state: "Arizona",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },
    {
      team_id: "sunset stallions",
      player_id: "ernestro ritter",
      team_name: "Sunset Stallions",
      player_name: "Ernestro Ritter",
      player_number: 32,
      position: "Attacker",
      player_class: "",
      hometown: "Chicago",
      state: "Illinois",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },
    {
      team_id: "3",
      player_id: "jerry middleton",
      team_name: "Sunset Stallions",
      player_name: "Jerry Middleton",
      player_number: 1,
      position: "Attacker",
      player_class: "",
      hometown: "Kansas City",
      state: "goalsouri",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "3",
      player_id: "emmitt coleman",
      team_name: "Sunset Stallions",
      player_name: "Emmitt Coleman",
      player_number: 1,
      position: "Attacker",
      player_class: "",
      hometown: "Arlington",
      state: "Texas",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },

    {
      team_id: "3",
      player_id: "roland tapia",
      team_name: "Oceanview Orcas",
      player_name: "Roland Tapia",
      player_number: 1,
      position: "Goalie",
      player_class: "",
      hometown: "Virginia Beach",
      state: "Virginia",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "oceanview orcas",
      player_id: "wilfred blackburn",
      team_name: "Oceanview Orcas",
      player_name: "Wilfred Blackburn",
      player_number: 1,
      position: "Defender",
      player_class: "",
      hometown: "Akron",
      state: "Ohio",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "oceanview orcas",
      player_id: "andreas rogers",
      team_name: "Oceanview Orcas",
      player_name: "Andreas Rogers",
      player_number: 1,
      position: "Defender",
      player_class: "",
      hometown: "",
      state: "",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "oceanview orcas",
      player_id: "rubin leblanc",
      team_name: "Oceanview Orcas",
      player_name: "Rubin Leblanc",
      player_number: 1,
      position: "Defender",
      player_class: "",
      hometown: "San Antonio",
      state: "Texas",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "oceanview orcas",
      player_id: "galen rosales",
      team_name: "Oceanview Orcas",
      player_name: "Galen Rosales",
      player_number: 45,
      position: "Midfielder",
      player_class: "",
      hometown: "Henderson",
      state: "Nevada",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "oceanview orcas",
      player_id: "felton poole",
      team_name: "Oceanview Orcas",
      player_name: "Felton Poole",
      player_number: 19,
      position: "Midfielder",
      player_class: "",
      hometown: "Boston",
      state: "Massachusetts",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "oceanview orcas",
      player_id: "herschel warner",
      team_name: "Oceanview Orcas",
      player_name: "Herschel Warner",
      player_number: 1,
      position: "Midfielder",
      player_class: "",
      hometown: "Lexington-Fayette",
      state: "Kentucky",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "oceanview orcas",
      player_id: "john david",
      team_name: "Oceanview Orcas",
      player_name: "John David",
      player_number: 8,
      position: "Attacker",
      player_class: "",
      hometown: "Tulsa",
      state: "Oklahoma",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "oceanview orcas",
      player_id: "nestor dominguez",
      team_name: "Oceanview Orcas",
      player_name: "Nestor Dominguez",
      player_number: 26,
      position: "Attacker",
      player_class: "",
      hometown: "Reno",
      state: "Nevada",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "oceanview orcas",
      player_id: "giovanni frank",
      team_name: "Oceanview Orcas",
      player_name: "Giovanni Frank",
      player_number: 6,
      position: "Attacker",
      player_class: "",
      hometown: "Milwaukee",
      state: "Wisconsin",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },

    {
      team_id: "highland wolves",
      player_id: "luis lambert",
      team_name: "Highland Wolves",
      player_name: "Luis Lambert",
      player_number: 1,
      position: "Goalie",
      player_class: "",
      hometown: "Anchorage",
      state: "Alaska",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "highland wolves",
      player_id: "eugenio howard",
      team_name: "Highland Wolves",
      player_name: "Eugenio Howard",
      player_number: 1,
      position: "Defender",
      player_class: "",
      hometown: "San Diego",
      state: "California",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "highland wolves",
      player_id: "Booker harvey",
      team_name: "Highland Wolves",
      player_name: "Booker Harvey",
      player_number: 1,
      position: "Defender",
      player_class: "",
      hometown: "Lincoln",
      state: "Nebraska",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "highland wolve",
      player_id: "mario hendrix",
      team_name: "Highland Wolves",
      player_name: "Mario Hendrix",
      player_number: 1,
      position: "Defender",
      player_class: "",
      hometown: "Madison",
      state: "Wisconsin",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "highland wolve",
      player_id: "jonas dyer",
      team_name: "Highland Wolves",
      player_name: "Jonas Dyer",
      player_number: 1,
      position: "Midfielder",
      player_class: "",
      hometown: "Norfolk",
      state: "Virginia",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0,
    },
    {
      team_id: "highland wolve",
      player_id: "richie macdonald",
      team_name: "Highland Wolves",
      player_name: "Richie Macdonald",
      player_number: 2,
      position: "Midfielder",
      player_class: "",
      hometown: "El Paso",
      state: "Texas",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "highland wolves",
      player_id: "cletus berger",
      team_name: "Highland Wolves",
      player_name: "Cletus Berger",
      player_number: 13,
      position: "Midfielder",
      player_class: "",
      hometown: "New Orleans",
      state: "Louisiana",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "highland wolves",
      player_id: "dalton reynolds",
      team_name: "Highland Wolves",
      player_name: "Dalton Reynolds",
      player_number: 50,
      position: "Attacker",
      player_class: "",
      hometown: "Dallas",
      state: "Texas",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "highland wolves",
      player_id: "elroy morrow",
      team_name: "Highland Wolves",
      player_name: "Elroy Morrow",
      player_number: 16,
      position: "Attacker",
      player_class: "",
      hometown: "St. Paul",
      state: "Minnesota",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "highland wolves",
      player_id: "Adan luna",
      team_name: "Highland Wolves",
      player_name: "Adan Luna",
      player_number: 9,
      position: "Attacker",
      player_class: "",
      hometown: "Scottsdale",
      state: "Arizona",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },

    {
      team_id: "forest falcons",
      player_id: "cornell arnold",
      team_name: "Forest Falcons",
      player_name: "Cornell Arnold",
      player_number: 1,
      position: "Goalie",
      player_class: "",
      hometown: "Lubbock",
      state: "Texas",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "forest falcons",
      player_id: "lonny wyatt",
      team_name: "Forest Falcons",
      player_name: "Lonny Wyatt",
      player_number: 1,
      position: "Defender",
      player_class: "",
      hometown: "Tampa",
      state: "Florida",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "forest falcons",
      player_id: "Earl schaefer",
      team_name: "Forest Falcons",
      player_name: "Earl Schaefer",
      player_number: 1,
      position: "Defender",
      player_class: "",
      hometown: "Fort Worth",
      state: "Texas",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "forest falcons",
      player_id: "robby rollins",
      team_name: "Forest Falcons",
      player_name: "Robby Rollins",
      player_number: 1,
      position: "Defender",
      player_class: "",
      hometown: "Pittsburgh",
      state: "Pennsylvania",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "forest falcons",
      player_id: "lawrence boyer",
      team_name: "Forest Falcons",
      player_name: "Lawrence Boyer",
      player_number: 1,
      position: "Midfielder",
      player_class: "",
      hometown: "Huntington",
      state: "New York",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "forest falcons",
      player_id: "elvin harmon",
      team_name: "Forest Falcons",
      player_name: "Elvin Harmon",
      player_number: 21,
      position: "Midfielder",
      player_class: "",
      hometown: "Boston",
      state: "Massachusetts",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "forest falcons",
      player_id: "sandy edwards",
      team_name: "Forest Falcons",
      player_name: "Sandy Edwards",
      player_number: 1,
      position: "Midfielder",
      player_class: "",
      hometown: "San Bernardino",
      state: "California",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "forest falcons",
      player_id: "ramon conway",
      team_name: "Forest Falcons",
      player_name: "Ramon Conway",
      player_number: 14,
      position: "Attacker",
      player_class: "",
      hometown: "Wichita",
      state: "Kansas",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "forest falcons",
      player_id: "brent cannon",
      team_name: "Forest Falcons",
      player_name: "Brent Cannon",
      player_number: 62,
      position: "Attacker",
      player_class: "",
      hometown: "Los Angeles",
      state: "California",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
    {
      team_id: "forest falcons",
      player_id: "gordon blackburn",
      team_name: "Forest Falcons",
      player_name: "Gordon Blackburn",
      player_number: 3,
      position: "Attacker",
      player_class: "",
      hometown: "Aurora",
      state: "Colorado",
      height_feet: 0,
      height_inches: 0,
      weight: 0,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      ground_balls: 0
    },
  ]
for (const player of players) {
    await addPlayer(player);
  }
}

async function dbinsert_Teams() {
  const teams: Team[] = [
    {  
      team_id: "maple hawks",
	    team_name: "Maple Hawks",
	    hometown: "Maple City",
	    state: "Arkansas",
	    coach: "John Rutherford",
    },
    { 
      team_id: "river raptors",
	    team_name: "River Raptors",
	    hometown: "River City",
	    state: "Arizona",
	    coach: "John Rutherford",

     },
    {  
      team_id: "sunset stallions",
	    team_name: "Sunset Stallions",
	    hometown: "Sunset City",
	    state: "California",
	    coach: "Ron Cassey",
    },
    {
      team_id: "oceanview orcas",
	    team_name: "Oceanview Orcas",
	    hometown: "Oceanview City",
	    state: "Florida",
	    coach: "Derek Smith",
     },
    {  
      team_id: "highland wolves",
	    team_name: "Highland Wolves",
	    hometown: "Highland City",
	    state: "Georgia",
	    coach: "Paul Jackson",
     },
    { 
      team_id: "forest falcons",
	    team_name: "Forest Falcons",
	    hometown: "Forest City",
	    state: "Illinois",
	    coach: "River Ross",

     }
  ];
  for (const team of teams) {
    await addTeam(team);
  }
}

async function dbinsert_Game() {
    const games : Game[] = [
        {
            game_id: "Maple Hawks vs River Raptors",
            hometeam: "MappleHawks",
            awayteam: "RiverRaptors",
            date: "2022-01-01",
            time: "1200",
            homescore: 0,
            awayscore: 0,
         
        },
        {
            game_id: "Sunset Stallions vs Oceanview Orcas",
            hometeam: "SunsetStallions",
            awayteam: "OceanviewOrcas",
            date: "2022-01-01",
            time: "1200",
            homescore: 0,
            awayscore: 0,
        },
        {
            game_id: "Highland Wolves vs Forest Falcons",
            hometeam: "HighlandWolves",
            awayteam: "ForestFalcons",
            date: "2022-01-01",
            time: "1200",
            homescore: 0,
            awayscore: 0,

        },
        {
            game_id: "Maple Hawks vs Sunset Stallions",
            hometeam: "MappleHawks",
            awayteam: "SunsetStallions",
            date: "2022-01-01",
            time: "1200",
            homescore: 0,
            awayscore: 0,
        },
        {
            game_id: "River Raptors vs Oceanview Orcas",
            hometeam: "RiverRaptors",
            awayteam: "OceanviewOrcas",
            date: "2022-01-01",
            time: "1200",
            homescore: 0,
            awayscore: 0,
          
        },
        {
            game_id: "Highland Wolves vs Maple Hawks",
            hometeam: "HighlandWolves",
            awayteam: "MappleHawks",
            date: "2022-01-01",
            time: "1200",
            homescore: 0,
            awayscore: 0,

        },
    ]
    for (const game of games) {
        await addGame(game);
    }
}

async function dbinsert_Sheet() {
    const sheets: Sheet[] = [
      { game_id: "Maple Hawks vs River Raptors", 
        sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef22a",
        scorekeeper: "Zachery Bowen",
      },
      { game_id: "Maple Hawks vs River Raptors", 
        sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef22R",
        scorekeeper: "Zachery Bowen" 
      },
      { game_id: "Sunset Stallions vs Oceanview Orcas",
        sheet_id: "4d945e5c-b133-4991-a14d-07595a4efRR2",
        scorekeeper: "Ernie Mayer"
      },
      { game_id: "Sunset Stallions vs Oceanview Orcas",
        sheet_id: "4d945e5c-b133-4991-a14d-07595a4efRR3",
        scorekeeper: "Ernie Mayer"
      },
      { game_id: "Highland Wolves vs Forest Falcons",
        sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef567",
        scorekeeper: "ron cassey"
      },
      { game_id: "Highland Wolves vs Forest Falcons",
        sheet_id: "14d945e5c-b133-4991-a14d-07595a4ef568",
        scorekeeper: "ron cassey"
      },
      { game_id: "Maple Hawks vs Sunset Stallions",
        sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef890",
        scorekeeper: "Zachery Bowen"
      },
      { game_id: "Maple Hawks vs Sunset Stallions",
        sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef22R678",
        scorekeeper: "Zachery Bowen"
      },
      { game_id: "River Raptors vs Oceanview Orcas",
        sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef901",
        scorekeeper: "Zachery Bowen"
      },
      { game_id: "River Raptors vs Oceanview Orcas",
        sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef22R123",
        scorekeeper: "Zachery Bowen"
      },
      { game_id: "Highland Wolves vs Maple Hawks",
        sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef529",
        scorekeeper: "Zachery Bowen"
      },
      { game_id: "Highland Wolves vs Maple Hawks",
        sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef521",
        scorekeeper: "Zachery Bowen"
      }
    ];
    for (const sheet of sheets) {
      await addSheet(sheet);
    }
}



async function dbinsert_SheetInfo() {
    const sheetinfos: SheetInfo[] = [
      {
        sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef22a",
        homecoach: "John Rutherford",
        awaycoach: "John Rutherford",
        hometeam: "string",
        awayteam: "string",
        date: "2022-01-01",
        site: "Maple College",
        start_time: "1200",
        scorekeeper: "Zachery Bowen",
        oppscorekeeper: "Jane Doe",
        timekeeper: "Alex Smith",
        head_official: "Chris Nguyen",
        umpire: "Jake Lee",
        field_judge: "Ryan Lee",
        lengthofquarters: " string",
        weathercondition: "string",
      },
      {
        sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef22R",
        homecoach: "John Rutherford",
        awaycoach: "John Rutherford",
        hometeam: "string",
        awayteam: "string",
        date: "2022-01-01",
        site: "Maple College",
        start_time: "1200",
        scorekeeper: "Zachery Bowen",
        oppscorekeeper: "Jane Doe",
        timekeeper: "Alex Smith",
        head_official: "Chris Nguyen",
        umpire: "Jake Lee",
        field_judge: "Ryan Lee",
        lengthofquarters: " string",
        weathercondition: "string",
      },
      {
        sheet_id: "4d945e5c-b133-4991-a14d-07595a4efRR2",
        homecoach: "John Rutherford",
        awaycoach: "John Rutherford",
        hometeam: "string",
        awayteam: "string",
        date: "2022-01-02",
        site: "Ocean College",
        start_time: "1200",
        scorekeeper: "Ernie Mayer",
        oppscorekeeper: "Jane Doe",
        timekeeper: "Alex Smith",
        head_official: "Chris Nguyen",
        umpire: "Jake Lee",
        field_judge: "Ryan Lee",
        lengthofquarters: " string",
        weathercondition: "string",
      },
      {
        sheet_id: "4d945e5c-b133-4991-a14d-07595a4efRR3",
        homecoach: "John Rutherford",
        awaycoach: "John Rutherford",
        hometeam: "string",
        awayteam: "string",
        date: "2022-01-02",
        site: "Ocean College",
        start_time: "1200",
        scorekeeper: "Ernie Mayer",
        oppscorekeeper: "Jane Doe",
        timekeeper: "Alex Smith",
        head_official: "Chris Nguyen",
        umpire: "Jake Lee",
        field_judge: "Ryan Lee",
        lengthofquarters: " string",
        weathercondition: "string",
      },
      {
        sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef567",
        homecoach: "ron cassey",
        awaycoach: "you",
        hometeam: "",
        awayteam: "",
        date: "2022-01-03",
        site: "Forest College",
        start_time: "1200",
        scorekeeper: "Johnnie Knapp",
        oppscorekeeper: "Jane Doe",
        timekeeper: "Alex Smith",
        head_official: "Chris Nguyen",
        umpire: "Jake Lee",
        field_judge: "Ryan Lee",
        lengthofquarters: "",
        weathercondition: "",
      },
      {
        sheet_id: "14d945e5c-b133-4991-a14d-07595a4ef568",
        homecoach: "ron cassey",
        awaycoach: "you",
        hometeam: "",
        awayteam: "",
        date: "2022-01-03",
        site: "Forest College",
        start_time: "1200",
        scorekeeper: "Johnnie Knapp",
        oppscorekeeper: "Jane Doe",
        timekeeper: "Alex Smith",
        head_official: "Chris Nguyen",
        umpire: "Jake Lee",
        field_judge: "Ryan Lee",
        lengthofquarters: "",
        weathercondition: "",
      },
      {
        sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef890",
        homecoach: "John Rutherford",
        awaycoach: "John Rutherford",
        hometeam: "string",
        awayteam: "string",
        date: "2022-01-04",
        site: "Sunset College",
        start_time: "1200",
        scorekeeper: "Sherman Alexander",
        oppscorekeeper: "Jane Doe",
        timekeeper: "Alex Smith",
        head_official: "Chris Nguyen",
        umpire: "Jake Lee",
        field_judge: "Ryan Lee",
        lengthofquarters: "",
        weathercondition: "  ",
      },
      {
        sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef22R678",
        homecoach: "John Rutherford",
        awaycoach: "John Rutherford",
        hometeam: "string",
        awayteam: "string",
        date: "2022-01-04",
        site: "Sunset College",
        start_time: "1200",
        scorekeeper: "Sherman Alexander",
        oppscorekeeper: "Jane Doe",
        timekeeper: "Alex Smith",
        head_official: "Chris Nguyen",
        umpire: "Jake Lee",
        field_judge: "Ryan Lee",
        lengthofquarters: "",
        weathercondition: "",
      },
      {
        sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef901",
        homecoach: "",
        awaycoach: "",
        hometeam: "",
        awayteam: "",
        date: "2022-01-05",
        site: "River College",
        start_time: "1200",
        scorekeeper: "Darrick Macdonald",
        oppscorekeeper: "Jane Doe",
        timekeeper: "Alex Smith",
        head_official: "Chris Nguyen",
        umpire: "Jake Lee",
        field_judge: "Ryan Lee",
        lengthofquarters: "",
        weathercondition: "",

      },
      {
        sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef22R123",
        homecoach: "",
        awaycoach: "",
        hometeam: "",
        awayteam: "",
        date: "2022-01-05",
        site: "River College",
        start_time: "1200",
        scorekeeper: "Darrick Macdonald",
        oppscorekeeper: "Jane Doe",
        timekeeper: "Alex Smith",
        head_official: "Chris Nguyen",
        umpire: "Jake Lee",
        field_judge: "Ryan Lee",
        lengthofquarters: "",
        weathercondition: "",
      },
      {
          sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef529",
          homecoach: "",
          awaycoach: "",
          hometeam: "",
          awayteam: "",
          date: "2022-01-06",
          site: "Highland College",
          start_time: "",
          scorekeeper: "Jonas Bryant",
          oppscorekeeper: "Jane Doe",
          timekeeper: "Alex Smith",
          head_official: "Chris Nguyen",
          umpire: "Jake Lee",
          field_judge: "Ryan Lee",
          lengthofquarters: "",
          weathercondition: "",
      },
      {
          sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef521",
          homecoach: "",
          awaycoach: "",
          hometeam: "",
          awayteam: "",
          date: "2022-01-06",
          site: "Highland College",
          start_time: "",
          scorekeeper: "Jonas Bryant",
          oppscorekeeper: "Jane Doe",
          timekeeper: "Alex Smith",
          head_official: "Chris Nguyen",
          umpire: "Jake Lee",
          field_judge: "Ryan Lee",
          lengthofquarters: "",
          weathercondition: "",
      },

    ];
    for (const stat of sheetinfos) {
      await addSheetInfo(stat);
    }
  }




async function dbinsert_Timeouts() {
  const timeouts: Timeout[] = [
    { sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef22a", side: 0, first_1_time: "", first_1_period: 0, first_2_time: "", first_2_period: 0, second_1_time: "", second_1_period: 0, second_2_time: "", second_2_period: 0, ot_1_time: "", ot_2_time: ""},
    { sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef22R", side: 1, first_1_time: "", first_1_period: 0, first_2_time: "",first_2_period: 0, second_1_time: "",  second_1_period: 0, second_2_time: "", second_2_period: 0, ot_1_time: "", ot_2_time: ""},
    { sheet_id: "4d945e5c-b133-4991-a14d-07595a4efRR2", side: 0, first_1_time: "", first_1_period: 0, first_2_time: "", first_2_period: 0, second_1_time: "", second_1_period: 0, second_2_time: "", second_2_period: 0, ot_1_time: "", ot_2_time: ""},
    { sheet_id: "4d945e5c-b133-4991-a14d-07595a4efRR3", side: 1, first_1_time: "", first_1_period: 0, first_2_time: "", first_2_period: 0, second_1_time: "", second_1_period: 0, second_2_time: "", second_2_period: 0, ot_1_time: "", ot_2_time: ""},
    { sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef567", side: 1, first_1_time: "", first_1_period: 0, first_2_time: "", first_2_period: 0, second_1_time: "", second_1_period: 0, second_2_time: "", second_2_period: 0, ot_1_time: "", ot_2_time: ""},
    { sheet_id: "14d945e5c-b133-4991-a14d-07595a4ef568", side: 0, first_1_time: "", first_1_period: 0, first_2_time: "", first_2_period: 0, second_1_time: "", second_1_period: 0, second_2_time: "", second_2_period: 0, ot_1_time: "", ot_2_time: ""},
    { sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef890", side: 1, first_1_time: "", first_1_period: 0, first_2_time: "", first_2_period: 0,second_1_time: "",  second_1_period: 0, second_2_time: "", second_2_period: 0, ot_1_time: "", ot_2_time: ""},
    { sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef22R678", side: 0, first_1_time: "", first_1_period: 0, first_2_time: "", first_2_period: 0, second_1_time: "", second_1_period: 0, second_2_time: "", second_2_period: 0, ot_1_time: "", ot_2_time: ""},
    { sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef901", side: 1, first_1_time: "", first_1_period: 0, first_2_time: "", first_2_period: 0, second_1_time: "", second_1_period: 0, second_2_time: "", second_2_period: 0, ot_1_time: "", ot_2_time: ""},
    { sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef22R123", side: 0, first_1_time: "", first_1_period: 0, first_2_time: "", first_2_period: 0, second_1_time: "", second_1_period: 0, second_2_time: "", second_2_period: 0, ot_1_time: "", ot_2_time: ""},
    { sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef529", side: 1, first_1_time: "", first_1_period: 0, first_2_time: "", first_2_period: 0, second_1_time: "", second_1_period: 0, second_2_time: "", second_2_period: 0, ot_1_time: "", ot_2_time: ""},
    { sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef521", side: 1, first_1_time: "", first_1_period: 0, first_2_time: "", first_2_period: 0, second_1_time: "", second_1_period: 0, second_2_time: "", second_2_period: 0, ot_1_time: "", ot_2_time: ""}
    
  ];
  for (const stat of timeouts) {
    await addTimeout(stat);
  }
}

async function dbinsert_Saves() {
  const saves: Save[] = [
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef22a",
      side: 0,
      player_number: 1,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
      
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef22a",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef22R",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef22R",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4efRR2",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4efRR2",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4efRR3",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4efRR3",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef567",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef567",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "14d945e5c-b133-4991-a14d-07595a4ef568",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "14d945e5c-b133-4991-a14d-07595a4ef568",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef890",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
      
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef890",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef22R678",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef22R678",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef901",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef901",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef22R123",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef22R123",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef529",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef529",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef521",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    },
    {
      sheet_id: "4d945e5c-b133-4991-a14d-07595a4ef521",
      side: 0,
      player_number: 0,
      quarter_1: 0,
      quarter_2: 0,
      quarter_3: 0,
      quarter_4: 0,
      ot: 0,
    }
  ];
  for (const stat of saves) {
    await addSave(stat);
  }
}

async function dbinsert_Penalties() {
  const penalties: Penalty[] = [
    { sheet_id: "", side: 0, index: 0, timeout:"", player_number: 23, infraction: "Holding", quarter: 1, time: "" },
    { sheet_id: "", side: 0, index: 1, timeout:"", player_number: 33, infraction: "Slashing", quarter: 2, time: "" },
    { sheet_id: "", side: 0, index: 0, timeout:"", player_number: 62, infraction: "Tripping", quarter: 2, time: "" },
    { sheet_id: "", side: 0, index: 0, timeout:"", player_number: 9, infraction: "Holding", quarter: 1, time: "" },
    { sheet_id: "", side: 0, index: 0, timeout:"", player_number: 1, infraction: "Slashing", quarter: 2, time: "" },
    { sheet_id: "", side: 0, index: 0, timeout:"", player_number: 27, infraction: "Tripping", quarter: 2, time: "" },
    { sheet_id: "", side: 0, index: 0, timeout:"", player_number: 6, infraction: "Holding", quarter: 1, time:"" },
    { sheet_id: "", side: 0, index: 0, timeout:"", player_number: 26, infraction: "Slashing", quarter: 2, time: "" },
    { sheet_id: "", side: 0, index: 0, timeout:"", player_number: 9, infraction: "Tripping", quarter: 2, time: "" },
    { sheet_id: "", side: 0, index: 0, timeout:"", player_number: 16, infraction: "Holding", quarter: 1, time: "" },
    { sheet_id: "", side: 0, index: 0, timeout:"", player_number: 3, infraction: "Slashing", quarter: 2, time: "" },
    { sheet_id: "", side: 0, index: 0, timeout:"", player_number: 62, infraction: "Tripping", quarter: 2, time: "" },
    { sheet_id: "", side: 0, index: 0, timeout:"", player_number: 23, infraction: "Holding", quarter: 1, time: "" },
    { sheet_id: "", side: 0, index: 0, timeout:"", player_number: 12, infraction: "Slashing", quarter: 2, time: "" },
    { sheet_id: "", side: 0, index: 0,timeout:"", player_number: 1, infraction: "Tripping", quarter: 2, time: "" },
    { sheet_id: "", side: 0, index: 0, timeout:"", player_number: 27, infraction: "Holding", quarter: 1, time: "" },
    { sheet_id: "", side: 0, index: 0,timeout:"", player_number: 62, infraction: "Slashing", quarter: 2, time: "" },
    { sheet_id: "", side: 0, index: 0, timeout:"", player_number: 9, infraction: "Tripping", quarter: 2, time: "" },
    { sheet_id: "", side: 0, index: 0, timeout:"", player_number: 6, infraction: "Holding", quarter: 1, time: "" },
    { sheet_id: "", side: 0,index: 0, timeout:"", player_number: 26, infraction: "Slashing", quarter: 2, time: "" },
    { sheet_id: "", side: 0, index: 0, timeout:"", player_number: 9, infraction: "Tripping", quarter: 2, time: "" },
    { sheet_id: "", side: 0,index: 0,  timeout:"", player_number: 16, infraction: "Holding", quarter: 1, time: "" },
    { sheet_id: "", side: 0, index: 0, timeout:"", player_number: 23, infraction: "Slashing", quarter: 2, time: "" },
    { sheet_id: "", side: 0, index: 0,timeout:"", player_number: 12, infraction: "Tripping", quarter: 2, time: "" }
  ];
  for (const stat of penalties) {
    await addPenalty(stat);
  }
}

async function dbinsert_IndividualScore() {
  const individualScores: IndividualScore[] = [
    { sheetid: "", side: "home", playerno: 23, player: "William Elder", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "home", playerno: 12, player: "Jerry Davidson", goals: 1, attempts: 4, fails: 3 },
    { sheetid: "", side: "home", playerno: 33, player: "Bob Sunny", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "home", playerno: 18, player: "Terry Cones", goals: 1, attempts: 4, fails: 3 },
    { sheetid: "", side: "home", playerno: 36, player: "Jackson Kaleb", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "home", playerno: 40, player: "Donald Right", goals: 1, attempts: 4, fails: 3 },
    { sheetid: "", side: "away", playerno: 62, player: "Emmanuel Hoffman", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 9, player: "Noel Wagner", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 23, player: "Jared Mcclure", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 13, player: "Brett Malone", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 5, player: "Rudy Mahoney", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 11, player: "Cameron Mercer", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "home", playerno: 1, player: "Emmitt Coleman", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "home", playerno: 27, player: "Jerry Middleton", goals: 1, attempts: 4, fails: 3 },
    { sheetid: "", side: "home", playerno: 32, player: "Ernestro Ritter", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "home", playerno: 12, player: "Alex Gillespire", goals: 1, attempts: 4, fails: 3 },
    { sheetid: "", side: "home", playerno: 17, player: "Amos Noble", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "home", playerno: 67, player: "Len Whitney", goals: 1, attempts: 4, fails: 3 },
    { sheetid: "", side: "away", playerno: 6, player: "Giovanni Frank", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 26, player: "Nestor Dominguez", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 8, player: "John David", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 67, player: "Herschel Warner", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 19, player: "Felton Poole", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 45, player: "Galen Rosales", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "home", playerno: 9, player: "Adan Luna", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "home", playerno: 16, player: "Elroy Morrow", goals: 1, attempts: 4, fails: 3 },
    { sheetid: "", side: "home", playerno: 50, player: "Dalton Reynolds", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "home", playerno: 13, player: "Cletus Berger", goals: 1, attempts: 4, fails: 3 },
    { sheetid: "", side: "home", playerno: 2, player: "Richie Macdonald", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "home", playerno: 10, player: "Jonas Dyerh", goals: 1, attempts: 4, fails: 3 },
    { sheetid: "", side: "away", playerno: 3, player: "Gordon Blackburn", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 62, player: "Brent Cannon", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 14, player: "Ramon Conway", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 70, player: "Sandy Edwards", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 21, player: "Elvin Harmon", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 31, player: "Lawrence Boyer", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "home", playerno: 23, player: "William Elder", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "home", playerno: 12, player: "Jerry Davidson", goals: 1, attempts: 4, fails: 3 },
    { sheetid: "", side: "home", playerno: 33, player: "Bob Sunny", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "home", playerno: 18, player: "Terry Cones", goals: 1, attempts: 4, fails: 3 },
    { sheetid: "", side: "home", playerno: 36, player: "Jackson Kaleb", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "home", playerno: 40, player: "Donald Right", goals: 1, attempts: 4, fails: 3 },
    { sheetid: "", side: "away", playerno: 1, player: "Emmitt Coleman", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "away", playerno: 27, player: "Jerry Middleton", goals: 1, attempts: 4, fails: 3 },
    { sheetid: "", side: "away", playerno: 32, player: "Ernestro Ritter", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "away", playerno: 12, player: "Alex Gillespire", goals: 1, attempts: 4, fails: 3 },
    { sheetid: "", side: "away", playerno: 17, player: "Amos Noble", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "away", playerno: 67, player: "Len Whitney", goals: 1, attempts: 4, fails: 3 },
    { sheetid: "", side: "home", playerno: 62, player: "Emmanuel Hoffman", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "home", playerno: 9, player: "Noel Wagner", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "home", playerno: 23, player: "Jared Mcclure", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "home", playerno: 13, player: "Brett Malone", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "home", playerno: 5, player: "Rudy Mahoney", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "home", playerno: 11, player: "Cameron Mercer", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 6, player: "Giovanni Frank", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 26, player: "Nestor Dominguez", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 8, player: "John David", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 67, player: "Herschel Warner", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 19, player: "Felton Poole", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "away", playerno: 45, player: "Galen Rosales", goals: 2, attempts: 3, fails: 1 },
    { sheetid: "", side: "home", playerno: 9, player: "Adan Luna", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "home", playerno: 16, player: "Elroy Morrow", goals: 1, attempts: 4, fails: 3 },
    { sheetid: "", side: "home", playerno: 50, player: "Dalton Reynolds", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "home", playerno: 13, player: "Cletus Berger", goals: 1, attempts: 4, fails: 3 },
    { sheetid: "", side: "home", playerno: 2, player: "Richie Macdonald", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "home", playerno: 10, player: "Jonas Dyerh", goals: 1, attempts: 4, fails: 3 },
    { sheetid: "", side: "away", playerno: 23, player: "William Elder", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "away", playerno: 12, player: "Jerry Davidson", goals: 1, attempts: 4, fails: 3 },
    { sheetid: "", side: "away", playerno: 33, player: "Bob Sunny", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "away", playerno: 18, player: "Terry Cones", goals: 1, attempts: 4, fails: 3 },
    { sheetid: "", side: "away", playerno: 36, player: "Jackson Kaleb", goals: 3, attempts: 5, fails: 2 },
    { sheetid: "", side: "away", playerno: 40, player: "Donald Right", goals: 1, attempts: 4, fails: 3 },
    
  ];
  for (const stat of individualScores) {
    await addIndividualScore(stat);
  }
}

async function dbinsert_GameStat() {
  const gameStats: GameStat[] = [
    {
      sheet_id: "101",
      side: 0,
      quarter: 1,
      ground: 2,
      shots: 6,
      clears_pass: 3,
      clears_fail: 1,
      extra_man_score: 1,
      extra_man_fail: 0,
      faceoff_win: 2,
      faceoff_loss: 1
    },
    {
      sheet_id: "101",
      side: 1,
      quarter: 1,
      ground: 1,
      shots: 4,
      clears_pass: 2,
      clears_fail: 2,
      extra_man_score: 0,
      extra_man_fail: 1,
      faceoff_win: 1,
      faceoff_loss: 3
    },
    {
      sheet_id: "102",
      side: 0,
      quarter: 2,
      ground: 5,
      shots: 7,
      clears_pass: 5,
      clears_fail: 0,
      extra_man_score: 2,
      extra_man_fail: 0,
      faceoff_win: 4,
      faceoff_loss: 1
    },
    {
      sheet_id: "102",
      side: 1,
      quarter: 1,
      ground: 2,
      shots: 6,
      clears_pass: 3,
      clears_fail: 1,
      extra_man_score: 1,
      extra_man_fail: 0,
      faceoff_win: 2,
      faceoff_loss: 1
    },
    {
      sheet_id: "103",
      side: 0,
      quarter: 1,
      ground: 1,
      shots: 4,
      clears_pass: 2,
      clears_fail: 2,
      extra_man_score: 0,
      extra_man_fail: 1,
      faceoff_win: 1,
      faceoff_loss: 3
    },
    {
      sheet_id: "103",
      side: 1,
      quarter: 1,
      ground: 2,
      shots: 6,
      clears_pass: 3,
      clears_fail: 1,
      extra_man_score: 1,
      extra_man_fail: 0,
      faceoff_win: 2,
      faceoff_loss: 1
    },
    {
      sheet_id: "104",
      side: 0,
      quarter: 1,
      ground: 1,
      shots: 4,
      clears_pass: 2,
      clears_fail: 2,
      extra_man_score: 0,
      extra_man_fail: 1,
      faceoff_win: 1,
      faceoff_loss: 3
    },
    {
      sheet_id: "104",
      side: 1,
      quarter: 1,
      ground: 2,
      shots: 6,
      clears_pass: 3,
      clears_fail: 1,
      extra_man_score: 1,
      extra_man_fail: 0,
      faceoff_win: 2,
      faceoff_loss: 1
    },
    {
      sheet_id: "105",
      side: 0,
      quarter: 1,
      ground: 1,
      shots: 4,
      clears_pass: 2,
      clears_fail: 2,
      extra_man_score: 0,
      extra_man_fail: 1,
      faceoff_win: 1,
      faceoff_loss: 3
    },
    {
      sheet_id: "105",
      side: 1,
      quarter: 1,
      ground: 2,
      shots: 6,
      clears_pass: 3,
      clears_fail: 1,
      extra_man_score: 1,
      extra_man_fail: 0,
      faceoff_win: 2,
      faceoff_loss: 1
    },
    {
      sheet_id: "106",
      side: 0,
      quarter: 1,
      ground: 1,
      shots: 4,
      clears_pass: 2,
      clears_fail: 2,
      extra_man_score: 0,
      extra_man_fail: 1,
      faceoff_win: 1,
      faceoff_loss: 3
    },
    {
      sheet_id: "106",
      side: 1,
      quarter: 1,
      ground: 1,
      shots: 4,
      clears_pass: 2,
      clears_fail: 2,
      extra_man_score: 0,
      extra_man_fail: 1,
      faceoff_win: 1,
      faceoff_loss: 3
    },
  ];
  for (const stat of gameStats) {
    await addGameStat(stat);
  }
}

