import sql from "$lib/database/postgres.server";
import type { Team } from "$lib/database/Team";
import type { Player } from "$lib/database/Team";
import { dbGameStatReset } from "$lib/database/gamestat";
import { dbIndividualScoreReset } from "$lib/database/individualscore";
import { dbPenaltyReset } from "$lib/database/penalties";
import { dbSaveReset } from "$lib/database/saves";
import { dbGameReset, dbSheetReset } from "$lib/database/sheets";
import { addPlayer, dbPlayersReset, dbTeamsReset } from "$lib/database/teams";
import { dbTimeoutReset } from "$lib/database/timeouts";
import { dbLoginReset } from "$lib/logon/logins";
import { dbGoalReset } from "./goals";
import { dbSheetInfoReset } from "./sheetinfos";
import { dbSheetPlayersReset } from "./sheetPlayers";

export async function dbReset() {
  await dbLoginReset();
  await dbGameReset();
  await dbSheetReset();
  await dbGameStatReset();
  await dbTeamsReset();
  await dbIndividualScoreReset();
  await dbPenaltyReset();
  await dbSaveReset();
  await dbPlayersReset();
  await dbTimeoutReset();
  await dbSheetInfoReset();
  await dbGoalReset();
  await dbSheetPlayersReset();

  await sql<Team[]>`
        INSERT INTO teams (TEAM_NAME, TEAM_ID, HOMETOWN, STATE, COACH) VALUES 
    (${"Notre Dame"}, ${"notredame"}, ${"Notre Dame"}, ${"IN"}, ${"Kevin Corrigan"})`;

  await sql<Team[]>`
        INSERT INTO teams (TEAM_NAME, TEAM_ID, HOMETOWN, STATE, COACH) VALUES 
    (${"Maryland"}, ${"maryland"}, ${"College Park"}, ${"MD"}, ${"John Tillman"})
    `;

  const notredamePlayers: Player[] = [
    {
      team_id: "notredame",
      player_id: "notredame-jaketaylor-13",
      team_name: "Notre Dame",
      player_name: "Jake Taylor",
      player_number: 13,
      position: "Attack",
      player_class: "Senior",
      hometown: "South Bend",
      state: "Indiana",
      height_feet: 6,
      height_inches: 1,
      weight: 210,
      quarters: 4,
      attempted_shots: 6,
      failed_shots: 2,
      goals: 3,
      assists: 5,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-chriskavanagh-50",
      team_name: "Notre Dame",
      player_name: "Chris Kavanagh",
      player_number: 50,
      position: "Attack",
      player_class: "Junior",
      hometown: "Glen Ridge",
      state: "New Jersey",
      height_feet: 5,
      height_inches: 11,
      weight: 185,
      quarters: 4,
      attempted_shots: 7,
      failed_shots: 1,
      goals: 4,
      assists: 4,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-patkavanagh-51",
      team_name: "Notre Dame",
      player_name: "Pat Kavanagh",
      player_number: 51,
      position: "Attack",
      player_class: "Senior",
      hometown: "Glen Ridge",
      state: "New Jersey",
      height_feet: 6,
      height_inches: 0,
      weight: 190,
      quarters: 4,
      attempted_shots: 8,
      failed_shots: 3,
      goals: 5,
      assists: 6,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-jordanfaison-14",
      team_name: "Notre Dame",
      player_name: "Jordan Faison",
      player_number: 14,
      position: "Mid",
      player_class: "Junior",
      hometown: "Denver",
      state: "Colorado",
      height_feet: 6,
      height_inches: 2,
      weight: 200,
      quarters: 4,
      attempted_shots: 4,
      failed_shots: 1,
      goals: 2,
      assists: 8,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-ericdobson-8",
      team_name: "Notre Dame",
      player_name: "Eric Dobson",
      player_number: 8,
      position: "Mid",
      player_class: "Senior",
      hometown: "Charlotte",
      state: "North Carolina",
      height_feet: 5,
      height_inches: 10,
      weight: 180,
      quarters: 4,
      attempted_shots: 5,
      failed_shots: 2,
      goals: 3,
      assists: 7,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-devonmclane-29",
      team_name: "Notre Dame",
      player_name: "Devon McLane",
      player_number: 29,
      position: "Mid",
      player_class: "Sophomore",
      hometown: "Albany",
      state: "New York",
      height_feet: 5,
      height_inches: 11,
      weight: 175,
      quarters: 4,
      attempted_shots: 3,
      failed_shots: 1,
      goals: 1,
      assists: 6,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-chrisconlin-20",
      team_name: "Notre Dame",
      player_name: "Chris Conlin",
      player_number: 20,
      position: "Defense",
      player_class: "Junior",
      hometown: "Boston",
      state: "Massachusetts",
      height_feet: 6,
      height_inches: 3,
      weight: 210,
      quarters: 4,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      assists: 9,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-marconapolitano-30",
      team_name: "Notre Dame",
      player_name: "Marco Napolitano",
      player_number: 30,
      position: "Defense",
      player_class: "Senior",
      hometown: "Long Island",
      state: "New York",
      height_feet: 6,
      height_inches: 4,
      weight: 215,
      quarters: 4,
      attempted_shots: 1,
      failed_shots: 0,
      goals: 1,
      assists: 8,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-shawnlyght-90",
      team_name: "Notre Dame",
      player_name: "Shawn Lyght",
      player_number: 90,
      position: "Defense",
      player_class: "Senior",
      hometown: "Washington D.C.",
      state: "District of Columbia",
      height_feet: 6,
      height_inches: 1,
      weight: 195,
      quarters: 4,
      attempted_shots: 2,
      failed_shots: 1,
      goals: 0,
      assists: 7,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-liamentenmann-44",
      team_name: "Notre Dame",
      player_name: "Liam Entenmann",
      player_number: 44,
      position: "Goalie",
      player_class: "Junior",
      hometown: "New York City",
      state: "New York",
      height_feet: 6,
      height_inches: 3,
      weight: 210,
      quarters: 4,
      attempted_shots: 15,
      failed_shots: 3,
      goals: 0,
      assists: 4,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-jefferyricciardelli-0",
      team_name: "Notre Dame",
      player_name: "Jeffery Ricciardelli",
      player_number: 0,
      position: "Attack",
      player_class: "Freshman",
      hometown: "Jersey City",
      state: "New Jersey",
      height_feet: 5,
      height_inches: 10,
      weight: 180,
      quarters: 2,
      attempted_shots: 3,
      failed_shots: 1,
      goals: 1,
      assists: 2,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-fultonbayman-2",
      team_name: "Notre Dame",
      player_name: "Fulton Bayman",
      player_number: 2,
      position: "Attack",
      player_class: "Sophomore",
      hometown: "Baltimore",
      state: "Maryland",
      height_feet: 6,
      height_inches: 0,
      weight: 195,
      quarters: 3,
      attempted_shots: 4,
      failed_shots: 2,
      goals: 2,
      assists: 3,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-colinhagstrom-4",
      team_name: "Notre Dame",
      player_name: "Colin Hagstrom",
      player_number: 4,
      position: "Mid",
      player_class: "Freshman",
      hometown: "Chicago",
      state: "Illinois",
      height_feet: 5,
      height_inches: 11,
      weight: 170,
      quarters: 1,
      attempted_shots: 2,
      failed_shots: 0,
      goals: 0,
      assists: 1,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-vrycewalker-5",
      team_name: "Notre Dame",
      player_name: "Vryce Walker",
      player_number: 5,
      position: "Mid",
      player_class: "Junior",
      hometown: "Denver",
      state: "Colorado",
      height_feet: 6,
      height_inches: 1,
      weight: 185,
      quarters: 3,
      attempted_shots: 3,
      failed_shots: 1,
      goals: 1,
      assists: 4,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-fisherfinley-6",
      team_name: "Notre Dame",
      player_name: "Fisher Finley",
      player_number: 6,
      position: "Mid",
      player_class: "Sophomore",
      hometown: "Charlotte",
      state: "North Carolina",
      height_feet: 5,
      height_inches: 9,
      weight: 175,
      quarters: 2,
      attempted_shots: 2,
      failed_shots: 1,
      goals: 0,
      assists: 3,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-willangrick-10",
      team_name: "Notre Dame",
      player_name: "Will Angrick",
      player_number: 10,
      position: "Mid",
      player_class: "Senior",
      hometown: "Pittsburgh",
      state: "Pennsylvania",
      height_feet: 6,
      height_inches: 2,
      weight: 200,
      quarters: 4,
      attempted_shots: 5,
      failed_shots: 2,
      goals: 2,
      assists: 6,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-tylerbuchner-12",
      team_name: "Notre Dame",
      player_name: "Tyler Buchner",
      player_number: 12,
      position: "Mid",
      player_class: "Freshman",
      hometown: "San Diego",
      state: "California",
      height_feet: 6,
      height_inches: 4,
      weight: 210,
      quarters: 1,
      attempted_shots: 1,
      failed_shots: 0,
      goals: 0,
      assists: 1,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-reillygray-17",
      team_name: "Notre Dame",
      player_name: "Reilly Gray",
      player_number: 17,
      position: "Defense",
      player_class: "Sophomore",
      hometown: "Pittsburgh",
      state: "Pennsylvania",
      height_feet: 6,
      height_inches: 0,
      weight: 205,
      quarters: 2,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      assists: 3,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-christianalacqua-19",
      team_name: "Notre Dame",
      player_name: "Christian Alacqua",
      player_number: 19,
      position: "Defense",
      player_class: "Junior",
      hometown: "Long Island",
      state: "New York",
      height_feet: 6,
      height_inches: 2,
      weight: 200,
      quarters: 3,
      attempted_shots: 1,
      failed_shots: 0,
      goals: 0,
      assists: 4,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-carterparlette-21",
      team_name: "Notre Dame",
      player_name: "Carter Parlette",
      player_number: 21,
      position: "Defense",
      player_class: "Senior",
      hometown: "Bethesda",
      state: "Maryland",
      height_feet: 6,
      height_inches: 1,
      weight: 215,
      quarters: 2,
      attempted_shots: 1,
      failed_shots: 0,
      goals: 0,
      assists: 5,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-willlynch-22",
      team_name: "Notre Dame",
      player_name: "Will Lynch",
      player_number: 22,
      position: "Defense",
      player_class: "Junior",
      hometown: "Boston",
      state: "Massachusetts",
      height_feet: 6,
      height_inches: 3,
      weight: 210,
      quarters: 4,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      assists: 7,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-maxbusenkell-23",
      team_name: "Notre Dame",
      player_name: "Max Busenkell",
      player_number: 23,
      position: "Defense",
      player_class: "Sophomore",
      hometown: "South Bend",
      state: "Indiana",
      height_feet: 6,
      height_inches: 2,
      weight: 190,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      assists: 2,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-benramsey-24",
      team_name: "Notre Dame",
      player_name: "Ben Ramsey",
      player_number: 24,
      position: "Mid",
      player_class: "Freshman",
      hometown: "Chicago",
      state: "Illinois",
      height_feet: 5,
      height_inches: 10,
      weight: 180,
      quarters: 2,
      attempted_shots: 2,
      failed_shots: 1,
      goals: 1,
      assists: 3,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-willmaheras-25",
      team_name: "Notre Dame",
      player_name: "Will Maheras",
      player_number: 25,
      position: "Mid",
      player_class: "Junior",
      hometown: "Philadelphia",
      state: "Pennsylvania",
      height_feet: 5,
      height_inches: 11,
      weight: 190,
      quarters: 4,
      attempted_shots: 4,
      failed_shots: 2,
      goals: 2,
      assists: 5,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-jalenseymour-26",
      team_name: "Notre Dame",
      player_name: "Jalen Seymour",
      player_number: 26,
      position: "Attack",
      player_class: "Sophomore",
      hometown: "Orlando",
      state: "Florida",
      height_feet: 6,
      height_inches: 0,
      weight: 185,
      quarters: 2,
      attempted_shots: 3,
      failed_shots: 0,
      goals: 1,
      assists: 4,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-rossburgmaster-27",
      team_name: "Notre Dame",
      player_name: "Ross Burgmaster",
      player_number: 27,
      position: "Defense",
      player_class: "Freshman",
      hometown: "Richmond",
      state: "Virginia",
      height_feet: 6,
      height_inches: 1,
      weight: 200,
      quarters: 3,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      assists: 4,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-nateschwitzenber-37",
      team_name: "Notre Dame",
      player_name: "Nate Schwitzenber",
      player_number: 37,
      position: "Attack",
      player_class: "Junior",
      hometown: "Pittsburgh",
      state: "Pennsylvania",
      height_feet: 6,
      height_inches: 3,
      weight: 195,
      quarters: 1,
      attempted_shots: 2,
      failed_shots: 1,
      goals: 1,
      assists: 2,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-willgallagher-47",
      team_name: "Notre Dame",
      player_name: "Will Gallagher",
      player_number: 47,
      position: "Mid",
      player_class: "Senior",
      hometown: "Boston",
      state: "Massachusetts",
      height_feet: 6,
      height_inches: 2,
      weight: 210,
      quarters: 3,
      attempted_shots: 4,
      failed_shots: 2,
      goals: 2,
      assists: 5,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-nickharris-77",
      team_name: "Notre Dame",
      player_name: "Nick Harris",
      player_number: 77,
      position: "Mid",
      player_class: "Sophomore",
      hometown: "Charlotte",
      state: "North Carolina",
      height_feet: 5,
      height_inches: 10,
      weight: 175,
      quarters: 2,
      attempted_shots: 1,
      failed_shots: 1,
      goals: 0,
      assists: 3,
      ground_balls: 0,
    },
    {
      team_id: "notredame",
      player_id: "notredame-willdonnovan-81",
      team_name: "Notre Dame",
      player_name: "Will Donnovan",
      player_number: 81,
      position: "Defense",
      player_class: "Freshman",
      hometown: "Long Island",
      state: "New York",
      height_feet: 6,
      height_inches: 3,
      weight: 210,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      assists: 2,
      ground_balls: 0,
    },
  ];

  const marylandPlayers: Player[] = [
    {
      team_id: "maryland",
      player_id: "maryland-ericspanos-7",
      team_name: "Maryland",
      player_name: "Eric Spanos",
      player_number: 7,
      position: "Attack",
      player_class: "Junior",
      hometown: "Baltimore",
      state: "Maryland",
      height_feet: 6,
      height_inches: 1,
      weight: 200,
      quarters: 3,
      attempted_shots: 5,
      failed_shots: 1,
      goals: 3,
      assists: 4,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-danielkelly-45",
      team_name: "Maryland",
      player_name: "Daniel Kelly",
      player_number: 45,
      position: "Attack",
      player_class: "Senior",
      hometown: "Phoenixville",
      state: "Pennsylvania",
      height_feet: 6,
      height_inches: 0,
      weight: 210,
      quarters: 4,
      attempted_shots: 7,
      failed_shots: 2,
      goals: 4,
      assists: 6,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-danielmaltz-37",
      team_name: "Maryland",
      player_name: "Daniel Maltz",
      player_number: 37,
      position: "Attack",
      player_class: "Sophomore",
      hometown: "Baltimore",
      state: "Maryland",
      height_feet: 6,
      height_inches: 4,
      weight: 215,
      quarters: 3,
      attempted_shots: 6,
      failed_shots: 2,
      goals: 2,
      assists: 5,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-ryansiracusa-38",
      team_name: "Maryland",
      player_name: "Ryan Siracusa",
      player_number: 38,
      position: "Mid",
      player_class: "Senior",
      hometown: "Rockville",
      state: "Maryland",
      height_feet: 6,
      height_inches: 0,
      weight: 190,
      quarters: 4,
      attempted_shots: 4,
      failed_shots: 1,
      goals: 1,
      assists: 4,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-ericmalever-4",
      team_name: "Maryland",
      player_name: "Eric Malever",
      player_number: 4,
      position: "Mid",
      player_class: "Junior",
      hometown: "Mamaroneck",
      state: "New York",
      height_feet: 6,
      height_inches: 1,
      weight: 185,
      quarters: 3,
      attempted_shots: 5,
      failed_shots: 1,
      goals: 2,
      assists: 5,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-jackkoras-22",
      team_name: "Maryland",
      player_name: "Jack Koras",
      player_number: 22,
      position: "Mid",
      player_class: "Freshman",
      hometown: "Annapolis",
      state: "Maryland",
      height_feet: 6,
      height_inches: 2,
      weight: 195,
      quarters: 2,
      attempted_shots: 3,
      failed_shots: 0,
      goals: 1,
      assists: 3,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-ajaxzappitello-1",
      team_name: "Maryland",
      player_name: "Ajax Zappitello",
      player_number: 1,
      position: "Defense",
      player_class: "Senior",
      hometown: "Philadelphia",
      state: "Pennsylvania",
      height_feet: 5,
      height_inches: 11,
      weight: 195,
      quarters: 4,
      attempted_shots: 1,
      failed_shots: 0,
      goals: 0,
      assists: 6,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-willschaller-27",
      team_name: "Maryland",
      player_name: "Will Schaller",
      player_number: 27,
      position: "Defense",
      player_class: "Junior",
      hometown: "Dallas",
      state: "Texas",
      height_feet: 6,
      height_inches: 1,
      weight: 210,
      quarters: 3,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      assists: 7,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-colinburlace-40",
      team_name: "Maryland",
      player_name: "Colin Burlace",
      player_number: 40,
      position: "Defense",
      player_class: "Junior",
      hometown: "Virginia Beach",
      state: "Virginia",
      height_feet: 6,
      height_inches: 3,
      weight: 215,
      quarters: 4,
      attempted_shots: 1,
      failed_shots: 0,
      goals: 0,
      assists: 8,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-loganmcnaney-30",
      team_name: "Maryland",
      player_name: "Logan McNaney",
      player_number: 30,
      position: "Goalie",
      player_class: "Senior",
      hometown: "Ellicott City",
      state: "Maryland",
      height_feet: 6,
      height_inches: 3,
      weight: 215,
      quarters: 4,
      attempted_shots: 12,
      failed_shots: 3,
      goals: 0,
      assists: 5,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-marcosignorello-3",
      team_name: "Maryland",
      player_name: "Marco Signorello",
      player_number: 3,
      position: "Defense",
      player_class: "Freshman",
      hometown: "Stamford",
      state: "Connecticut",
      height_feet: 6,
      height_inches: 2,
      weight: 200,
      quarters: 1,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      assists: 2,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-erickolar-8",
      team_name: "Maryland",
      player_name: "Eric Kolar",
      player_number: 8,
      position: "Mid",
      player_class: "Sophomore",
      hometown: "Elkridge",
      state: "Maryland",
      height_feet: 6,
      height_inches: 0,
      weight: 190,
      quarters: 2,
      attempted_shots: 1,
      failed_shots: 0,
      goals: 0,
      assists: 3,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-bradenerksa-10",
      team_name: "Maryland",
      player_name: "Braden Erksa",
      player_number: 10,
      position: "Attack",
      player_class: "Freshman",
      hometown: "Denver",
      state: "Colorado",
      height_feet: 6,
      height_inches: 3,
      weight: 205,
      quarters: 2,
      attempted_shots: 3,
      failed_shots: 1,
      goals: 1,
      assists: 4,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-zackwhittier-13",
      team_name: "Maryland",
      player_name: "Zack Whittier",
      player_number: 13,
      position: "Mid",
      player_class: "Sophomore",
      hometown: "Washington",
      state: "D.C.",
      height_feet: 5,
      height_inches: 11,
      weight: 175,
      quarters: 1,
      attempted_shots: 2,
      failed_shots: 0,
      goals: 1,
      assists: 2,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-charliekoras-14",
      team_name: "Maryland",
      player_name: "Charlie Koras",
      player_number: 14,
      position: "Attack",
      player_class: "Junior",
      hometown: "Annapolis",
      state: "Maryland",
      height_feet: 6,
      height_inches: 0,
      weight: 185,
      quarters: 3,
      attempted_shots: 4,
      failed_shots: 1,
      goals: 2,
      assists: 4,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-colinsharkey-24",
      team_name: "Maryland",
      player_name: "Colin Sharkey",
      player_number: 24,
      position: "Defense",
      player_class: "Junior",
      hometown: "Lutherville",
      state: "Maryland",
      height_feet: 6,
      height_inches: 2,
      weight: 210,
      quarters: 3,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      assists: 5,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-ajlarkin-26",
      team_name: "Maryland",
      player_name: "AJ Larkin",
      player_number: 26,
      position: "Mid",
      player_class: "Freshman",
      hometown: "Richmond",
      state: "Virginia",
      height_feet: 5,
      height_inches: 9,
      weight: 175,
      quarters: 1,
      attempted_shots: 1,
      failed_shots: 0,
      goals: 0,
      assists: 2,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-geordyholmes-34",
      team_name: "Maryland",
      player_name: "Geordy Holmes",
      player_number: 34,
      position: "Mid",
      player_class: "Sophomore",
      hometown: "Lutherville",
      state: "Maryland",
      height_feet: 6,
      height_inches: 1,
      weight: 190,
      quarters: 2,
      attempted_shots: 2,
      failed_shots: 1,
      goals: 1,
      assists: 3,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-jackbrennan-41",
      team_name: "Maryland",
      player_name: "Jack Brennan",
      player_number: 41,
      position: "Defense",
      player_class: "Senior",
      hometown: "Bethesda",
      state: "Maryland",
      height_feet: 6,
      height_inches: 3,
      weight: 215,
      quarters: 3,
      attempted_shots: 1,
      failed_shots: 0,
      goals: 0,
      assists: 6,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-griffinkinge-42",
      team_name: "Maryland",
      player_name: "Griffin Kinge",
      player_number: 42,
      position: "Mid",
      player_class: "Freshman",
      hometown: "Silver Spring",
      state: "Maryland",
      height_feet: 6,
      height_inches: 2,
      weight: 200,
      quarters: 2,
      attempted_shots: 3,
      failed_shots: 1,
      goals: 1,
      assists: 3,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-elijahstobaugh-44",
      team_name: "Maryland",
      player_name: "Elijah Stobaugh",
      player_number: 44,
      position: "Defense",
      player_class: "Sophomore",
      hometown: "Towson",
      state: "Maryland",
      height_feet: 6,
      height_inches: 0,
      weight: 210,
      quarters: 3,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      assists: 4,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-nickredd-47",
      team_name: "Maryland",
      player_name: "Nick Redd",
      player_number: 47,
      position: "Attack",
      player_class: "Junior",
      hometown: "Columbus",
      state: "Ohio",
      height_feet: 5,
      height_inches: 11,
      weight: 180,
      quarters: 1,
      attempted_shots: 2,
      failed_shots: 0,
      goals: 1,
      assists: 2,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-jacksoncanfield-50",
      team_name: "Maryland",
      player_name: "Jackson Canfield",
      player_number: 50,
      position: "Goalie",
      player_class: "Freshman",
      hometown: "South Orange",
      state: "New Jersey",
      height_feet: 6,
      height_inches: 4,
      weight: 210,
      quarters: 2,
      attempted_shots: 8,
      failed_shots: 2,
      goals: 0,
      assists: 4,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-jackmcdonald-51",
      team_name: "Maryland",
      player_name: "Jack McDonald",
      player_number: 51,
      position: "Defense",
      player_class: "Senior",
      hometown: "Fallston",
      state: "Maryland",
      height_feet: 6,
      height_inches: 3,
      weight: 220,
      quarters: 3,
      attempted_shots: 1,
      failed_shots: 0,
      goals: 0,
      assists: 7,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-lukewierman-52",
      team_name: "Maryland",
      player_name: "Luke Wierman",
      player_number: 52,
      position: "Mid",
      player_class: "Sophomore",
      hometown: "Annapolis",
      state: "Maryland",
      height_feet: 6,
      height_inches: 1,
      weight: 200,
      quarters: 4,
      attempted_shots: 4,
      failed_shots: 2,
      goals: 2,
      assists: 5,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-georgestamos-54",
      team_name: "Maryland",
      player_name: "George Stamos",
      player_number: 54,
      position: "Mid",
      player_class: "Junior",
      hometown: "Towson",
      state: "Maryland",
      height_feet: 6,
      height_inches: 2,
      weight: 190,
      quarters: 2,
      attempted_shots: 3,
      failed_shots: 1,
      goals: 1,
      assists: 4,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-owenmurphy-55",
      team_name: "Maryland",
      player_name: "Owen Murphy",
      player_number: 55,
      position: "Attack",
      player_class: "Freshman",
      hometown: "Baltimore",
      state: "Maryland",
      height_feet: 5,
      height_inches: 10,
      weight: 170,
      quarters: 1,
      attempted_shots: 2,
      failed_shots: 0,
      goals: 1,
      assists: 2,
      ground_balls: 0,
    },
    {
      team_id: "maryland",
      player_id: "maryland-nickalviti-77",
      team_name: "Maryland",
      player_name: "Nick Alviti",
      player_number: 77,
      position: "Defense",
      player_class: "Sophomore",
      hometown: "Garden City",
      state: "New York",
      height_feet: 6,
      height_inches: 2,
      weight: 205,
      quarters: 3,
      attempted_shots: 0,
      failed_shots: 0,
      goals: 0,
      assists: 5,
      ground_balls: 0,
    },
  ];

  for (const player of notredamePlayers) {
    addPlayer(player);
  }

  for (const player of marylandPlayers) {
    addPlayer(player);
  }

  //     await sql<Player[]>`
  //         INSERT INTO players (
  //     team_id, player_id, team_name, player_name, player_number, position, player_class, hometown,
  //     state, height_feet, height_inches, weight, quarters, attempted_shots, failed_shots, goals, ground_balls)
  //     VALUES
  //     (1, 101, 'Notre Dame', 'Jake Taylor', 13, 'Attack', 'Senior', 'South Bend', 'Indiana', 6, 1, 210, 4, 6, 2, 3, 5),
  //     (1, 102, 'Notre Dame', 'Chris Kavanagh', 50, 'Attack', 'Junior', 'Glen Ridge', 'New Jersey', 5, 11, 185, 4, 7, 1, 4, 4),
  //     (1, 103, 'Notre Dame', 'Pat Kavanagh', 51, 'Attack', 'Senior', 'Glen Ridge', 'New Jersey', 6, 0, 190, 4, 8, 3, 5, 6),
  //     (1, 104, 'Notre Dame', 'Jordan Faison', 14, 'Mid', 'Junior', 'Denver', 'Colorado', 6, 2, 200, 4, 4, 1, 2, 8),
  //     (1, 105, 'Notre Dame', 'Eric Dobson', 8, 'Mid', 'Senior', 'Charlotte', 'North Carolina', 5, 10, 180, 4, 5, 2, 3, 7),
  //     (1, 106, 'Notre Dame', 'Devon McLane', 29, 'Mid', 'Sophomore', 'Albany', 'New York', 5, 11, 175, 4, 3, 1, 1, 6),
  //     (1, 107, 'Notre Dame', 'Chris Conlin', 20, 'Defense', 'Junior', 'Boston', 'Massachusetts', 6, 3, 210, 4, 0, 0, 0, 9),
  //     (1, 108, 'Notre Dame', 'Marco Napolitano', 30, 'Defense', 'Senior', 'Long Island', 'New York', 6, 4, 215, 4, 1, 0, 1, 8),
  //     (1, 109, 'Notre Dame', 'Shawn Lyght', 90, 'Defense', 'Senior', 'Washington D.C.', 'District of Columbia', 6, 1, 195, 4, 2, 1, 0, 7),
  //     (1, 110, 'Notre Dame', 'Liam Entenmann', 44, 'Goalie', 'Junior', 'New York City', 'New York', 6, 3, 210, 4, 15, 3, 0, 4),
  //     (1, 111, 'Notre Dame', 'Jeffery Ricciardelli', 0, 'Attack', 'Freshman', 'Jersey City', 'New Jersey', 5, 10, 180, 2, 3, 1, 1, 2),
  //     (1, 112, 'Notre Dame', 'Fulton Bayman', 2, 'Attack', 'Sophomore', 'Baltimore', 'Maryland', 6, 0, 195, 3, 4, 2, 2, 3),
  //     (1, 113, 'Notre Dame', 'Colin Hagstrom', 4, 'Mid', 'Freshman', 'Chicago', 'Illinois', 5, 11, 170, 1, 2, 0, 0, 1),
  //     (1, 114, 'Notre Dame', 'Vryce Walker', 5, 'Mid', 'Junior', 'Denver', 'Colorado', 6, 1, 185, 3, 3, 1, 1, 4),
  //     (1, 115, 'Notre Dame', 'Fisher Finley', 6, 'Mid', 'Sophomore', 'Charlotte', 'North Carolina', 5, 9, 175, 2, 2, 1, 0, 3),
  //     (1, 116, 'Notre Dame', 'Will Angrick', 10, 'Mid', 'Senior', 'Pittsburgh', 'Pennsylvania', 6, 2, 200, 4, 5, 2, 2, 6),
  //     (1, 117, 'Notre Dame', 'Tyler Buchner', 12, 'Mid', 'Freshman', 'San Diego', 'California', 6, 4, 210, 1, 1, 0, 0, 1),
  //     (1, 118, 'Notre Dame', 'Reilly Gray', 17, 'Defense', 'Sophomore', 'Pittsburgh', 'Pennsylvania', 6, 0, 205, 2, 0, 0, 0, 3),
  //     (1, 119, 'Notre Dame', 'Christian Alacqua', 19, 'Defense', 'Junior', 'Long Island', 'New York', 6, 2, 200, 3, 1, 0, 0, 4),
  //     (1, 120, 'Notre Dame', 'Carter Parlette', 21, 'Defense', 'Senior', 'Bethesda', 'Maryland', 6, 1, 215, 2, 1, 0, 0, 5),
  //     (1, 121, 'Notre Dame', 'Will Lynch', 22, 'Defense', 'Junior', 'Boston', 'Massachusetts', 6, 3, 210, 4, 0, 0, 0, 7),
  //     (1, 122, 'Notre Dame', 'Max Busenkell', 23, 'Defense', 'Sophomore', 'South Bend', 'Indiana', 6, 2, 190, 1, 0, 0, 0, 2),
  //     (1, 123, 'Notre Dame', 'Ben Ramsey', 24, 'Mid', 'Freshman', 'Chicago', 'Illinois', 5, 10, 180, 2, 2, 1, 1, 3),
  //     (1, 124, 'Notre Dame', 'Will Maheras', 25, 'Mid', 'Junior', 'Philadelphia', 'Pennsylvania', 5, 11, 190, 4, 4, 2, 2, 5),
  //     (1, 125, 'Notre Dame', 'Jalen Seymour', 26, 'Attack', 'Sophomore', 'Orlando', 'Florida', 6, 0, 185, 2, 3, 0, 1, 4),
  //     (1, 126, 'Notre Dame', 'Ross Burgmaster', 27, 'Defense', 'Freshman', 'Richmond', 'Virginia', 6, 1, 200, 3, 0, 0, 0, 4),
  //     (1, 127, 'Notre Dame', 'Nate Schwitzenber', 37, 'Attack', 'Junior', 'Pittsburgh', 'Pennsylvania', 6, 3, 195, 1, 2, 1, 1, 2),
  //     (1, 128, 'Notre Dame', 'Will Gallagher', 47, 'Mid', 'Senior', 'Boston', 'Massachusetts', 6, 2, 210, 3, 4, 2, 2, 5),
  //     (1, 129, 'Notre Dame', 'Nick Harris', 77, 'Mid', 'Sophomore', 'Charlotte', 'North Carolina', 5, 10, 175, 2, 1, 1, 0, 3),
  //     (1, 130, 'Notre Dame', 'Will Donnovan', 81, 'Defense', 'Freshman', 'Long Island', 'New York', 6, 3, 210, 1, 0, 0, 0, 2);
  //     `

  //     await sql<Player[]>`
  //     INSERT INTO players (
  //     team_id, player_id, team_name, player_name, player_number, position, player_class, hometown,
  //     state, height_feet, height_inches, weight, quarters, attempted_shots, failed_shots, goals, ground_balls)
  //     VALUES
  //     (2, 201, 'Maryland', 'Eric Spanos', 7, 'Attack', 'Junior', 'Baltimore', 'Maryland', 6, 1, 200, 3, 5, 1, 3, 4),
  //     (2, 202, 'Maryland', 'Daniel Kelly', 45, 'Attack', 'Senior', 'Phoenixville', 'Pennsylvania', 6, 0, 210, 4, 7, 2, 4, 6),
  //     (2, 203, 'Maryland', 'Daniel Maltz', 37, 'Attack', 'Sophomore', 'Baltimore', 'Maryland', 6, 4, 215, 3, 6, 2, 2, 5),
  //     (2, 204, 'Maryland', 'Ryan Siracusa', 38, 'Mid', 'Senior', 'Rockville', 'Maryland', 6, 0, 190, 4, 4, 1, 1, 4),
  //     (2, 205, 'Maryland', 'Eric Malever', 4, 'Mid', 'Junior', 'Mamaroneck', 'New York', 6, 1, 185, 3, 5, 1, 2, 5),
  //     (2, 206, 'Maryland', 'Jack Koras', 22, 'Mid', 'Freshman', 'Annapolis', 'Maryland', 6, 2, 195, 2, 3, 0, 1, 3),
  //     (2, 207, 'Maryland', 'Ajax Zappitello', 1, 'Defense', 'Senior', 'Philadelphia', 'Pennsylvania', 5, 11, 195, 4, 1, 0, 0, 6),
  //     (2, 208, 'Maryland', 'Will Schaller', 27, 'Defense', 'Junior', 'Dallas', 'Texas', 6, 1, 210, 3, 0, 0, 0, 7),
  //     (2, 209, 'Maryland', 'Colin Burlace', 40, 'Defense', 'Junior', 'Virginia Beach', 'Virginia', 6, 3, 215, 4, 1, 0, 0, 8),
  //     (2, 210, 'Maryland', 'Logan McNaney', 30, 'Goalie', 'Senior', 'Ellicott City', 'Maryland', 6, 3, 215, 4, 12, 3, 0, 5),
  //     (2, 211, 'Maryland', 'Marco Signorello', 3, 'Defense', 'Freshman', 'Stamford', 'Connecticut', 6, 2, 200, 1, 0, 0, 0, 2),
  //     (2, 212, 'Maryland', 'Eric Kolar', 8, 'Mid', 'Sophomore', 'Elkridge', 'Maryland', 6, 0, 190, 2, 1, 0, 0, 3),
  //     (2, 213, 'Maryland', 'Braden Erksa', 10, 'Attack', 'Freshman', 'Denver', 'Colorado', 6, 3, 205, 2, 3, 1, 1, 4),
  //     (2, 214, 'Maryland', 'Zack Whittier', 13, 'Mid', 'Sophomore', 'Washington', 'D.C.', 5, 11, 175, 1, 2, 0, 1, 2),
  //     (2, 215, 'Maryland', 'Charlie Koras', 14, 'Attack', 'Junior', 'Annapolis', 'Maryland', 6, 0, 185, 3, 4, 1, 2, 4),
  //     (2, 216, 'Maryland', 'Colin Sharkey', 24, 'Defense', 'Junior', 'Lutherville', 'Maryland', 6, 2, 210, 3, 0, 0, 0, 5),
  //     (2, 217, 'Maryland', 'AJ Larkin', 26, 'Mid', 'Freshman', 'Richmond', 'Virginia', 5, 9, 175, 1, 1, 0, 0, 2),
  //     (2, 218, 'Maryland', 'Geordy Holmes', 34, 'Mid', 'Sophomore', 'Lutherville', 'Maryland', 6, 1, 190, 2, 2, 1, 1, 3),
  //     (2, 219, 'Maryland', 'Jack Brennan', 41, 'Defense', 'Senior', 'Bethesda', 'Maryland', 6, 3, 215, 3, 1, 0, 0, 6),
  //     (2, 220, 'Maryland', 'Griffin Kinge', 42, 'Mid', 'Freshman', 'Silver Spring', 'Maryland', 6, 2, 200, 2, 3, 1, 1, 3),
  //     (2, 221, 'Maryland', 'Elijah Stobaugh', 44, 'Defense', 'Sophomore', 'Towson', 'Maryland', 6, 0, 210, 3, 0, 0, 0, 4),
  //     (2, 222, 'Maryland', 'Nick Redd', 47, 'Attack', 'Junior', 'Columbus', 'Ohio', 5, 11, 180, 1, 2, 0, 1, 2),
  //     (2, 223, 'Maryland', 'Jackson Canfield', 50, 'Goalie', 'Freshman', 'South Orange', 'New Jersey', 6, 4, 210, 2, 8, 2, 0, 4),
  //     (2, 224, 'Maryland', 'Jack McDonald', 51, 'Defense', 'Senior', 'Fallston', 'Maryland', 6, 3, 220, 3, 1, 0, 0, 7),
  //     (2, 225, 'Maryland', 'Luke Wierman', 52, 'Mid', 'Sophomore', 'Annapolis', 'Maryland', 6, 1, 200, 4, 4, 2, 2, 5),
  //     (2, 226, 'Maryland', 'George Stamos', 54, 'Mid', 'Junior', 'Towson', 'Maryland', 6, 2, 190, 2, 3, 1, 1, 4),
  //     (2, 227, 'Maryland', 'Owen Murphy', 55, 'Attack', 'Freshman', 'Baltimore', 'Maryland', 5, 10, 170, 1, 2, 0, 1, 2),
  //     (2, 228, 'Maryland', 'Nick Alviti', 77, 'Defense', 'Sophomore', 'Garden City', 'New York', 6, 2, 205, 3, 0, 0, 0, 5);`
}
