export interface SheetInfo {
    sheet_id: string,
    homecoach: string,
    awaycoach: string,
    hometeam: string,
    awayteam: string,
    date: string,
    site: string,
    start_time: string,
    scorekeeper: string,
    oppscorekeeper: string,
    timekeeper: string,
    head_official: string,
    umpire: string,
    field_judge: string,
    lengthofquarters: string,
    weathercondition: string,
}