import type { Player } from "./Team";

export const auburnLacrosseRoster: Player[] = [
  {
    team_name: "Auburn University",
    player_name: "Sarver Adams",
    player_number: 14,
    position: "Midfield",
    quarters: 0,
    attempted_shots: 0,
    goals: 0,
    failed_shots: 0,
    ground_balls: 0,
    player_class: "",
    hometown: "",
    state: "",
    height_feet: 0,
    height_inches: 0,
    weight: 0,
    team_id: "auburnuniversity",
    player_id: "auburnuniversity-sarveradams-14",
    assists: 0
  },
  {
    team_name: "Auburn University",
    player_name: "Brooks Andrus",
    player_number: 6,
    position: "FOGO",
    quarters: 0,
    attempted_shots: 0,
    goals: 0,
    failed_shots: 0,
    ground_balls: 0,
    player_class: "",
    hometown: "",
    state: "",
    height_feet: 0,
    height_inches: 0,
    weight: 0,
    team_id: "auburnuniversity",
    player_id: "auburnuniversity-brooksandrus-6",
    assists: 0
  },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Dominic Annichiarico",
  //   player_number: 4,
  //   position: "SSDM",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Ben Auger",
  //   player_number: 37,
  //   position: "SSDM",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Carter Calagis",
  //   player_number: 2,
  //   position: "LSM",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Ryan Comeau",
  //   player_number: 42,
  //   position: "Attack",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Sean Connolly",
  //   player_number: 48,
  //   position: "Attack",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Eamon Cummins",
  //   player_number: 45,
  //   position: "Defense",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Deric De Angelis",
  //   player_number: 19,
  //   position: "Defense",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Reece Defilippis",
  //   player_number: 24,
  //   position: "Attack",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Jackson Derrick",
  //   player_number: 9,
  //   position: "Midfield",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Michael Duffy",
  //   player_number: 77,
  //   position: "Attack",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Colby Erdossy",
  //   player_number: 41,
  //   position: "Attack",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Max Forsyth",
  //   player_number: 27,
  //   position: "Midfield",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Aidan Garrett",
  //   player_number: 13,
  //   position: "FOGO",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Yates Holley",
  //   player_number: 12,
  //   position: "SSDM",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Jack Hooper",
  //   player_number: 43,
  //   position: "FOGO",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Jackson Hursey",
  //   player_number: 49,
  //   position: "LSM",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Hunter Hyderally",
  //   player_number: 20,
  //   position: "Attack",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Caleb Karonka",
  //   player_number: 29,
  //   position: "SSDM",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Seth Kerr",
  //   player_number: 16,
  //   position: "Attack",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Michael Kotarski",
  //   player_number: 7,
  //   position: "Midfield",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Casey Lencioni",
  //   player_number: 3,
  //   position: "Midfield",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Mikey Lencioni",
  //   player_number: 21,
  //   position: "SSDM",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Ricardo Lizardi-Nazario",
  //   player_number: 66,
  //   position: "Defense",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Matijs Lobato",
  //   player_number: 55,
  //   position: "Midfield",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Myles Lobato",
  //   player_number: 5,
  //   position: "Midfield",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Andrew Luff",
  //   player_number: 8,
  //   position: "Midfield",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Graham Lyle",
  //   player_number: 23,
  //   position: "Defense",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "James Maher",
  //   player_number: 32,
  //   position: "SSDM",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Jamy Maroney",
  //   player_number: 10,
  //   position: "Attack",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Parker Mason",
  //   player_number: 26,
  //   position: "Defense",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Chris Michals",
  //   player_number: 30,
  //   position: "SSDM",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Colson Miller",
  //   player_number: 99,
  //   position: "Goalie",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Craig Morgan",
  //   player_number: 34,
  //   position: "Goalie",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Preston Morrison",
  //   player_number: 28,
  //   position: "Defense",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Ethan Mott",
  //   player_number: 25,
  //   position: "Defense",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Max Pearson",
  //   player_number: 11,
  //   position: "SSDM",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Rob Pilla",
  //   player_number: 88,
  //   position: "Attack",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Ethan Pustizzi",
  //   player_number: 18,
  //   position: "Defense",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "Auburn University Men's Lacrosse",
  //   player_name: "Landon Reichert",
  //   player_number: 17,
  //   position: "Goalie",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "auburn-mlax-001",
  //   player_id: ""
  // },
];

export const uahLacrosseRoster: Player[] = [
  {
    team_name: "UAH",
    player_name: "James Alford",
    player_number: 15,
    position: "Attack",
    quarters: 0,
    attempted_shots: 0,
    goals: 0,
    failed_shots: 0,
    ground_balls: 0,
    player_class: "",
    hometown: "",
    state: "",
    height_feet: 0,
    height_inches: 0,
    weight: 0,
    team_id: "uah",
    player_id: "uah-jamesalford-15",
    assists: 0
  },
  {
    team_name: "UAH",
    player_name: "Alex Bass",
    player_number: 16,
    position: "Midfield",
    quarters: 0,
    attempted_shots: 0,
    goals: 0,
    failed_shots: 0,
    ground_balls: 0,
    player_class: "",
    hometown: "",
    state: "",
    height_feet: 0,
    height_inches: 0,
    weight: 0,
    team_id: "uah",
    player_id: "uah-alexbass-16",
    assists: 0
  },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Ben Bernhardt",
  //   player_number: 14,
  //   position: "Defense",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Ethan Bird",
  //   player_number: 6,
  //   position: "Midfield",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Trey Clonts",
  //   player_number: 11,
  //   position: "Attack",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Will Conner",
  //   player_number: 4,
  //   position: "Defense",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Bryce Foster",
  //   player_number: 21,
  //   position: "Goalie",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Hunter Freeman",
  //   player_number: 17,
  //   position: "Midfield",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Gavin Hayes",
  //   player_number: 10,
  //   position: "Attack",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Grayson Hilton",
  //   player_number: 20,
  //   position: "Attack",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Andrew Jones",
  //   player_number: 8,
  //   position: "Midfield",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Isaac King",
  //   player_number: 5,
  //   position: "Defense",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Dylan Lange",
  //   player_number: 12,
  //   position: "Defense",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Connor Matthews",
  //   player_number: 7,
  //   position: "SSDM",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Charlie Moody",
  //   player_number: 3,
  //   position: "Attack",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Nick Patterson",
  //   player_number: 9,
  //   position: "Goalie",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Sam Phillips",
  //   player_number: 2,
  //   position: "Attack",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Jake Ragan",
  //   player_number: 18,
  //   position: "Defense",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Blake Rhodes",
  //   player_number: 22,
  //   position: "Midfield",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Liam Taylor",
  //   player_number: 23,
  //   position: "SSDM",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Caleb Thomas",
  //   player_number: 13,
  //   position: "FOGO",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Ethan Wilson",
  //   player_number: 24,
  //   position: "Midfield",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
  // {
  //   team_name: "UAH Men's Lacrosse",
  //   player_name: "Zachary Wood",
  //   player_number: 19,
  //   position: "Defense",
  //   quarter: 0,
  //   shots: 0,
  //   goals: 0,
  //   miss: 0,
  //   ground: 0,
  //   player_class: "",
  //   hometown: "",
  //   state: "",
  //   height_feet: 0,
  //   height_inches: 0,
  //   weight: 0,
  //   team_id: "uah-mlax-001",
  //   player_id: ""
  // },
];
